---
- name: Preflight - Fail if target host is not stable for this Role.
  ansible.builtin.fail:
    msg: "This role is not stable for the target operating system, {{ ansible_distribution }} {{ ansible_distribution_major_version }}."
  when: (ansible_distribution is not defined) or
        (ansible_distribution_version is not defined) or
        (ansible_distribution+" "+ansible_distribution_major_version not in unattended_upgrade_stable_os)

- name: "Include Derivate specific Variables."
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  changed_when: 'false'
  failed_when: 'false'

- name: "Include Distribution specific Variables."
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  changed_when: 'false'
  failed_when: 'false'

- name: "Include Package Manager specific Playbook."
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}.yml"
